sudo: false
dist: trusty
language: node_js
branches:
  only:
    - master
jobs:
  fast_finish: true
  allow_failures:
    - env: WEBPACK_VERSION=canary
    - node_js: 9
  include:
    - &test-latest
      stage: Webpack latest
      node_js: 6
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:$JOB_PART
    - <<: *test-latest
      node_js: 8
      env: WEBPACK_VERSION=latest JOB_PART=lint
      script: npm run travis:$JOB_PART
    - <<: *test-latest
      node_js: 8
      env: WEBPACK_VERSION=latest JOB_PART=coverage
      script: npm run travis:$JOB_PART
      after_success: 'bash <(curl -s https://codecov.io/bash)'
    - stage: Webpack canary
      node_js: 8
      env: WEBPACK_VERSION=4.0.0-alpha.0 JOB_PART=test
      script: npm run travis:$JOB_PART
    - stage: NodeJS Next
      node_js: 9
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:$JOB_PART
before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^5.0.0; fi'
  - nvm --version
  - node --version
  - npm --version
before_script:
  - |-
    if [ "$WEBPACK_VERSION" ]; then
      npm i --no-save webpack@$WEBPACK_VERSION
    fi
script:
  - 'npm run travis:$JOB_PART'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
